{% set version = '1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-robustrankaggreg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RobustRankAggreg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RobustRankAggreg/RobustRankAggreg_{{ version }}.tar.gz
  sha256: 23ab88f6f1e56ae85a45bf5107ad0c37202dde275d799ed9fe214a1ab2c754df

build:
  merge_build_host: True  # [win]
  number: 1004
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('RobustRankAggreg')"           # [not win]
    - "\"%R%\" -e \"library('RobustRankAggreg')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RobustRankAggreg
  license: GPL-2.0-only
  summary: Methods for aggregating ranked lists, especially lists of genes. It implements the
    Robust Rank Aggregation (Kolde et. al in preparation) and some other simple algorithms
    for the task. RRA method uses a probabilistic model for aggregation that is robust
    to noise and also facilitates the calculation of significance probabilities for
    all the elements in the final ranking.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - FrodePedersen
    - ArneKr
    - MathiasHaudgaard

# Package: RobustRankAggreg
# Type: Package
# Title: Methods for robust rank aggregation
# Version: 1.1
# Date: 2010-11-14
# Author: Raivo Kolde, Sven Laur
# Maintainer: Raivo Kolde <rkolde@gmail.com>
# Description: Methods for aggregating ranked lists, especially lists of genes. It implements the Robust Rank Aggregation (Kolde et. al in preparation) and some other simple algorithms for the task. RRA method uses a probabilistic model for aggregation that is robust to noise and also facilitates the calculation of significance probabilities for all the elements in the final ranking.
# License: GPL-2
# LazyLoad: yes
# Depends: methods
# Collate: 'aggregateRanks.R'
# Packaged: 2013-06-03 14:46:02 UTC; kolde
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-06-03 17:47:53
