travis:
  secure:
    BINSTAR_TOKEN: MSw8uxlj6TBL9ri7KyAxW8ObJ1mDVt9i+VxRNxyKzkNxt6CW/bcAgreimfg5KtKW5M9rFaf9h1aCyhXN1y/Ckm6jhVHVihzeljuUuDLtSauqZaG/5jorNYSksQ6Fyd2WaR12riL+zSiXPPSw1iTGveB/RbC4cA5vAXYs+CqLP+0rYb9/+9cksWdTAQpyl46TFn9E8YRbxSTmgu/trRnmzMEBg1bsGjDk3OLdPM3zkkzk2YgnzJb/8b4Ynt/cvjfITQ/cBcw/RTx5oWT0WWtfiWrLdvcJ/tJdVeE+h2qoKNZRXAIp+9dRvPDYgqWYBR0lRiP+2zEC9PYuvpDB//15f4IVJpa84lMyrbax8ZrwYHuMTnB8k+YqKyO0iOWYCfgjKSuu0TXe/LlE8TkVhXcxKswYEyEXDCzdAV7EmoQKgmNFiOLztnxVc6rid3TU3xLGp+1c9z+JlFQa6NHjdM+M2C7vr0K5FCvDdof+/avtel/83koRdXsqaVjKNg/1pJ1vjzSpJO+urZkoxtDE0jpPAQ17/CfSdp6btKEvcjWiJvC3fHV6UIuSwlzxkG+1kQPJ5IleSLfcT1fhmOr/LiHqvf+beCCYt09tZUH0bdz8FBtqTPydhGAToKN9jVEVlEaeAokT34rwUMM7O6eLI3C1wuU/6H5jewgmhpy5vBKDaIY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
