travis:
  secure:
    BINSTAR_TOKEN: JdLZksEt1eG5nAd4QXUqi+q7tBjZCQsJh8E3xA0L+5q+ZejdlwTJvSUnB7hzwBQ37p3SzFS7eK6fjbHIieAeGnbWpDdsQRE21vrdzVdqiCAHk6syyDahkL3Yxfdk7o8NxEvETCtvPS2xSx813978E1eLKu8jyKrLQjq2uIpgUdzSlSAyYWvOOIFTVQgB4GuxleHNxrWFFIKK0tyh7Xks0zbI68vXWD8MDLdsL9ONk6Yw3M2UST07KZrr8hY/dayJaqgK5ubVARY8M/KOepzBVzvVcKEl/QXXxpMYVeL9ErM6gWzx+y7J9nJfssqtyRQBJja4sqOREsOkRlnJ1s2+MQet9IoHF9CPkt6D9kS9F7JwDPU3Cciie6vThRGO0hW+xfmLOXrVDiFG1QHpuhx9CCwirN2NNsAWTd0pnkkBlqx0vWnBI8F5JNOybGokYmrKeEPOsOjOU1cBDO17kLzK2CfefH157VIGRydBFDeThdT2YnKXK3tu4XhYau7buQuxBVcn0OogRNn+3AQ2hoLR+4dWY9K29uwSsUnrNmP1sQo57ZMBwLr8iXbJdQvHcNUNopvi8GMJRadvac5ayyK1+0l+kqtIjWa9WTNUSfsBvmkbNyflhTdz8pH088qrTNOhlVQ4y+g6/ZvFBxFR14jmUVUPBl4NKZk3frCyCmh7kII=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
