travis:
  secure:
    BINSTAR_TOKEN: fEXLCCHv/bUjwkR8jUaQWBCZj7nfHEvUj/C9bBMUc5fXFsP3b3Vyk4E/dOyykt+fUqzw0LAi60U+SHGFrR1q4mw7EXQGvVjmWbP4RKb6AWg4lVt/FXvRTFYpSN3FsIK91TTwcFmiVZjT1wfgGJR21TweM/TSU69i9ygCkNRNmEhLURJAXxOayIJi3HoudCNcpSrHEPYQyroQd3mXUJXxzEaHfSuLfNMKLAer5kE14QO58EN8Ai2jhZr1f0MOGQjH52KOTGcbJO/aPmEqBhs4bTFtE6lcs+lxqQXily+X4025vCamVU0ZR/MbU6dAG6ehKLjVuNkdivcfxSUHHUyCBz1bKjdMlXFt4Cjkgi2ORc5fzfAxovKRx99T0UPATGksFLGikoQCQIzexMt2+GROCfF6FsQ3VPs0uHbbWj6BbJp8KQ8YuypzoYOGoGJAHYueWntMcyeiSR6C+Q5efMS5D5dVumvjwVBt2v0a5HV5GoGNooObeYUV1wvc6iosQkpV01kO/ELmPl/wcMiEaRKnRdd5riq1JM9l6LxhZNgv7IH323QVHqpHQso1yAAxAS7zNM/DD0Q7lKhc4GDB45ZcSNgkx7LvJ7eA1WDc8IwP1dhBksP74VElj4USiqbmJVufYU7dByroWRN5LzFSvEim1V7mJo+UH4//0omtAUWHpKg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
